Update CI and Readme
pollination/pollination-apps pull request #9
Opened 2022-06-16 21:15 UTC by devngc

- Improved instruction in readme
- Added the docker build and semantic release to CI
- Added releaserc to the template

2022-06-16 21:20 UTC, devngc commented
You might ask me why I have a step to generate app name. Firstly, It uses the repo name as the app name. This will be useful if the user wants to change the name of the app. They can just rename the repository rather than generate the whole new template using the `pollination-apps new` command. Secondly, it makes sure the app name is lowercase.

2022-06-20 19:41 UTC, mostaphaRoudsari requested changes

2022-06-20 19:41 UTC, mostaphaRoudsari commented on pollination_apps/template/assets/{{cookiecutter.project_slug}}/README.md
> +   **Note** that the commit messages with only `fix` and `feat` type will trigger a deployment to Pollination.
This is really complicated for a typical user. If you want to change the CI to use the semantic release, then it should be an option. We will have 3 options: no CI, manual versioning, automated versioning

2022-06-20 21:40 UTC, devngc commented on pollination_apps/template/assets/{{cookiecutter.project_slug}}/README.md
> +   **Note** that the commit messages with only `fix` and `feat` type will trigger a deployment to Pollination.
@mostaphaRoudsari, if a user wants to use their own version numbers then why would they go the GitHub route? They would simply use the command line.

2022-06-20 23:25 UTC, mostaphaRoudsari commented on pollination_apps/template/assets/{{cookiecutter.project_slug}}/README.md
> +   **Note** that the commit messages with only `fix` and `feat` type will trigger a deployment to Pollination.
I disagree. Setting up the CI to push the app to Pollination once a new release is created on GitHub is an improvement and I think we should consider it as an option.

2022-06-24 16:18 UTC, mostaphaRoudsari approved these changes
Thanks, @devngc! LGTM.

2022-06-24 16:18 UTC, merged